# Generated by Django 6.1 on 2026-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=20)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_real', models.DecimalField(decimal_places=2, default=0, help_text='Preencher caso o ingrediente tenha faltado', max_digits=10)),
                ('vencido', models.BooleanField(default=False, help_text='O ingrediente estragou/venceu?')),
                ('faltou_antes_do_fim', models.BooleanField(default=False, help_text='Acabou antes do mês terminar?')),
            ],
        ),
    ]
